### ISSUE TITLE
Nom à trouver pour l'app

### ISSUE THREAD

**Issue by infoapplis** [paceuniversity/M4S2016team1#1]
Hi, j'ai ouvert cet issus pour que l'on puisse réfléchir sur le nom que nous allons donné à notre application. Vos idées sont les bienvenues afin que nous puissions choisir un nom qui décrit l'application.

**Comment by infoapplis** [comment]
J'ai pensé à "Collab-Etu" comme nom. Dites moi ce que vous en pensé. J'attends aussi vos propositions de nom. A bientôt.

**Comment by leonieNd** [comment]
Moi je propose Sharetude ! ou Universchool !

**Comment by nellyamaylis** [comment]
Collab-Etu je trouve çà cool comme nom. 
Moi je pensais à "StudAide"  ou "ScoolCollab"

**Comment by nellyamaylis** [comment]
Sharetude belle combinaison

**Comment by nellyamaylis** [comment]
Ou "Reviz"

**Comment by infoapplis** [comment]
C'est super ! On se rapproche, je pense qu'on ne va pas tardé à trouver le nom. Nous avons 6 propositions de nom qui sont interessantes.
- Collab-Etu
- Sharetude
- Universchool
- StudAide
- ScoolCollab
- Reviz

Je propose que nous procédons par élimination s'il n'y a pas d'autres propositions. Essayons de voir parmi ces noms celui qui se rapproche le plus de ce qu'on veut faire. Un nom qui soit facile à retenir, et qui permet de vendre l'app par exemple.

**Comment by leonieNd** [comment]
1 - Universchool : assez généraliste des fonctionnalités
2 - Collab-Etu : montre bien le concepte
3 - Sharetude : rejoins le 2- je pense que c'est juste histoire de la langue 

French or English ?

```
StudAide : j'accroche pas 
ScoolCollab : trop lours selon moi
Reviz : ne represente qu'une partie de l'application
```

**Comment by infoapplis** [comment]
Bien résumé @leonieNd. Je pense que le nom dépend aussi des cibles. Nous visons les étudiants qui vivent au Sénégal ? En Afrique ? Ou bien dans le monde ? C'est très important, ça permet aux futures utilisateurs de s'approprier de l'app.

**Comment by leonieNd** [comment]
Pour la localité à nous dans décider ! Moi je dirait dans le monde car le contenu peut etre adapter suivant le pays ( je vx dire les versions) par contre changer de nom parce que au début c'était une application pour les sénégalais plus finalement pour des asiatiques  ça serait compliqué lol . Moi je dirait donc Mondial pour le nom

**Comment by infoapplis** [comment]
Ce sont toutes de belles propositions. Pour ma part je pense que "Reviz" sonne bien pour l'app. Rien qu'avec le nom on peut avoir un aperçut des fonctionnalités offertes par l'app avant même de consulter la fiche de détail. En même temps comme @leonieNd vient de le mentionné, cela ne concerne qu'une partie des fonctionnalités de l'app. Mais il n'est pas aussi nécessaire que le nom de l'app puisse regrouper toutes les fonctionnalités de cette dernière.
Le concept que nous souhaitons mettre en place c'est "réviser en collaboration". Nous avons d'une part "Révision" et d'autre part "Collaboration".

**Comment by infoapplis** [comment]
Pour la localité, c'est assez complexe et je pense qu'on va devoir faire un choix car, les réalités ne sont pas les mêmes et aussi les programmes. A mon avis le programme d'enseignement du Sénégal peut être différent de celui du Bénin ou d'un pays de l'Asie.
Pour un début, je propose qu'on commence petit. Choisissons un pays pour commencer nous élargirons au fur et à mesure que nous avançons (ça peut prendre des années !).

**Comment by infoapplis** [comment]
Il y a aussi un autre facteur qui ne joue pas à notre faveur, c'est le temps. Nous devons produire des prototypes les mardi et vendredi. Donc il faut qu'on synthétise l'information et se concentré sur un domaine bien définie pour éviter de se perdre.

**Comment by infoapplis** [comment]
Consultez le wiki, j'ai mis un schéma qui résume les fonctionnalités de l'app. Dites moi ce que vous en pensé (des remarques, des suggestions, ...)

**Comment by leonieNd** [comment]
Pour la localités je suis ok niveau fonctionnalités et donner ? Je parler d'avoir un nom assez "ouvert " pouvant toucher le monde entier .
Il faut qu'on fasse des lots de fonctionnalités à couvrir dans un premier temps. En prendre 2 à 3 à modéliser puis intégrer faire cela à la suite !

Et super nos brainstorming , j'adore comme chacun amène son idée et que tout ce mélange je serait partante pour que ça soit pareil pour le design et la suite. 

J'ai revu le wiki bon j'avais pas réfléchi sur le sujet et donc je vais revoir pour s'il y'a des suggestions. Sinon j'ai apprécié :+1:

**Comment by infoapplis** [comment]
Oui, en effet c'est hyper cool de partager les avis, c'est ce qu'on appel un travail d'équipe !
Et pour les autres étapes aussi ça sera pareil. On maintien le cap.

**Comment by nellyamaylis** [comment]
Je suis d'accord avec vous mais j'ai proposé reviz aussi dans l'optique aussi de pouvoir jouer avec le Z et je trouvais les autres trop long. Sharetude aussi on peux jouer avec le E qui est au milieu et avoir un beau logo.
Je passe voir le wiki et je vous reviens

**Comment by infoapplis** [comment]
J'ai fini avec le Design and Paper mais j'ai du mal à faire un commit. Dès que j'y remédie, je vous envoi les images.

**Comment by nellyamaylis** [comment]
D'accord! Mais quel est le problème pour le commit?

**Comment by infoapplis** [comment]
Cool @nellyamaylis, si je résume bien il y a deux noms qui sortent du lot :
Reviz et ShareEtude !

**Comment by leonieNd** [comment]
ahh ahah nelly tu m'as fait rire déjà pour le nom tu pense au design !! you right j'y avait pas pensé

**Comment by infoapplis** [comment]
Si je fais un commit, il y a un message qui me dit de vérifier l'état du répertoire car, il y a une erreur.

**Comment by leonieNd** [comment]
tu as fait un clone du répertoire projet ??

**Comment by infoapplis** [comment]
Oui j'ai cloner le répertoire. Hier même j'ai posté une image laba. Peut-être que c'est due à la connexion.

**Comment by nellyamaylis** [comment]
peut etre ou tu as ajouté un truc dans le répertoire sans savoir?

**Comment by leonieNd** [comment]
ah ok ben bonne résolution alors moi seul git status est mon secours le reste j'y connais pas ....

**Comment by infoapplis** [comment]
J'ai redémarrer la machine, pour l'instant ça tourne. J'attends de voir ce que ça va donner. Merci !

**Comment by leonieNd** [comment]
# **ReviZ**
